version: "3.7"

services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.10.2"
    restart: "always"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"
    networks:
      - "public"
    ports:
      - "9200:9200/tcp"

  rabbitmq:
    image: "rabbitmq:3.7.17-management-alpine"
    restart: "always"
    environment:
      RABBITMQ_ERLANG_COOKIE: "${APP_RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${APP_RABBITMQ_USERNAME}"
      RABBITMQ_DEFAULT_PASS: "${APP_RABBITMQ_PASSWORD}"
    networks:
      - "public"
    ports:
      - "5672:5672/tcp"
      - "15672:15672/tcp"

volumes:

  elasticsearch_data:

networks:

  public:
    name: public
