version: "3.7"

services:

  rethinkdb:
    image: "rethinkdb:2.4.1-buster-slim"
    restart: "always"
    command: "rethinkdb --bind all --initial-password ${APP_RETHINKDB_PASSWORD}"
    networks:
      - "public"
    volumes:
      - "rethinkdb_data:/data"
    ports:
      - "8080:8080/tcp"
      - "28015:28015/tcp"

  rabbitmq:
    image: "rabbitmq:3.7.17-management-alpine"
    restart: "always"
    environment:
      RABBITMQ_ERLANG_COOKIE: "${APP_RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${APP_RABBITMQ_USERNAME}"
      RABBITMQ_DEFAULT_PASS: "${APP_RABBITMQ_PASSWORD}"
    networks:
      - public
    ports:
      - "5672:5672/tcp"
      - "15672:15672/tcp"

volumes:

  rethinkdb_data:

networks:

  public:
    name: public
