version: "3.7"

services:

  rethinkdb:
    image: "rethinkdb:2.4.1-buster-slim"
    restart: "always"
    command: "rethinkdb --bind all --initial-password ${APP_RETHINKDB_PASSWORD}"
    networks:
      - "public"
    volumes:
      - "rethinkdb_data:/data"
    ports:
      - "8080:8080/tcp"
      - "28015:28015/tcp"

volumes:

  rethinkdb_data:

networks:

  public:
    name: public
