name: moleculer tests

defaults:
  run:
    working-directory: ./

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  linter:
    runs-on: ubuntu-latest
    container:
      image: node:12.19-alpine3.9
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install packages
        run: yarn
      - name: Run standard linter
        run: yarn standard
        env:
          NODE_ENV: test

  tests:
    runs-on: ubuntu-latest
    container:
      image: node:12.19-alpine3.9
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install packages
        run: yarn
      - name: Run tests for moleculer
        run: yarn test:moleculer
        env:
          NODE_ENV: test
      - name: Cache coverage
        uses: actions/upload-artifact@v2
        with:
          name: artifact-coverage
          path: coverage

  coverage:
    needs: [linter,tests]
    runs-on: ubuntu-latest
    container:
      image: node:12.19-alpine3.9
    steps:
      - name: Update alpine packages
        run: apk add --update bash curl git
      - name: Restore coverage
        uses: actions/download-artifact@v2
        with:
          name: artifact-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.2.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: Moleculer
          directory: ./coverage
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.txt
