name: Moleculer

defaults:
  run:
    working-directory: ./

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  linter:
    runs-on: ubuntu-latest
    container:
      image: node:12.19-alpine3.9
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - run: yarn standard
        env:
          NODE_ENV: test
  tests:
    needs: linter
    runs-on: ubuntu-latest
    container:
      image: node:12.19-alpine3.9
    steps:
      - uses: actions/checkout@v1
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: Moleculer
          directory: ./coverage
          files: clover.xml
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.txt
      - run: yarn
      - run: yarn test:moleculer
        env:
          NODE_ENV: test
