name: Moleculer

defaults:
  run:
    working-directory: ./

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  linter:
    runs-on: ubuntu-latest
    container:
      image: node:12.19-alpine3.9
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install packages
        run: yarn
      - name: Run standard linter
        run: yarn standard
        env:
          NODE_ENV: test

  tests:
    runs-on: ubuntu-latest
    container:
      image: node:12.19-alpine3.9
    steps:
      - name: Update alpine packages
        run: apk add --update bash curl
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install packages
        run: yarn
      - name: Run tests for moleculer
        run: yarn test:moleculer
        env:
          NODE_ENV: test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.2.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: Moleculer
          directory: ./coverage
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.txt

# - name: Restore node_modules
#   uses: actions/download-artifact@v2
#   with:
#     name: artifact-node_modules
#
# - name: Cache node_modules
#   uses: actions/upload-artifact@v2
#   with:
#     name: artifact-node_modules
#     path: node_modules
